<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>BrepLoopList.Add Method (BrepLoopType, BrepFace)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Collections.BrepLoopList.Add(Rhino.Geometry.BrepLoopType,Rhino.Geometry.BrepFace)" /><meta name="Description" content="Create a new boundary loop on a face. After you get this BrepLoop, you still need to create the vertices, edges, and trims that define the loop." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry.Collections" /><meta name="file" content="M_Rhino_Geometry_Collections_BrepLoopList_Add_1" /><meta name="guid" content="M_Rhino_Geometry_Collections_BrepLoopList_Add_1" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_Geometry_Collections.htm" title="Rhino.Geometry.Collections" tocid="N_Rhino_Geometry_Collections">Rhino.Geometry.Collections</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_Geometry_Collections_BrepLoopList.htm" title="BrepLoopList Class" tocid="T_Rhino_Geometry_Collections_BrepLoopList">BrepLoopList Class</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Methods_T_Rhino_Geometry_Collections_BrepLoopList.htm" title="BrepLoopList Methods" tocid="Methods_T_Rhino_Geometry_Collections_BrepLoopList">BrepLoopList Methods</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Collections_BrepLoopList_Add.htm" title="Add Method " tocid="Overload_Rhino_Geometry_Collections_BrepLoopList_Add">Add Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Collections_BrepLoopList_Add.htm" title="Add Method (BrepLoopType)" tocid="M_Rhino_Geometry_Collections_BrepLoopList_Add">Add Method (BrepLoopType)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Collections_BrepLoopList_Add_1.htm" title="Add Method (BrepLoopType, BrepFace)" tocid="M_Rhino_Geometry_Collections_BrepLoopList_Add_1">Add Method (BrepLoopType, BrepFace)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">BrepLoopList<span id="LSTAAD75C6C_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTAAD75C6C_0?cpp=::|nu=.");</script>Add Method (BrepLoopType, BrepFace)</td></tr></table><span class="introStyle">Rhino 5 for Windows</span><div class="summary">
            Create a new boundary loop on a face.  After you get this
            BrepLoop, you still need to create the vertices, edges, 
            and trims that define the loop.
            </div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_Geometry_Collections.htm">Rhino.Geometry.Collections</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.30000.16 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">BrepLoop</span> <span class="identifier">Add</span>(
	<span class="identifier">BrepLoopType</span> <span class="parameter">loopType</span>,
	<span class="identifier">BrepFace</span> <span class="parameter">face</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">Add</span> ( 
	<span class="parameter">loopType</span> <span class="keyword">As</span> <span class="identifier">BrepLoopType</span>,
	<span class="parameter">face</span> <span class="keyword">As</span> <span class="identifier">BrepFace</span>
) <span class="keyword">As</span> <span class="identifier">BrepLoop</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">loopType</span></dt><dd>Type: <a href="T_Rhino_Geometry_BrepLoopType.htm">Rhino.Geometry<span id="LSTAAD75C6C_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTAAD75C6C_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BrepLoopType</a><br /><p style="color: #dc143c; font-size: 8.5pt; font-weight: bold;">[Missing &lt;param name="loopType"/&gt; documentation for "M:Rhino.Geometry.Collections.BrepLoopList.Add(Rhino.Geometry.BrepLoopType,Rhino.Geometry.BrepFace)"]</p></dd><dt><span class="parameter">face</span></dt><dd>Type: <a href="T_Rhino_Geometry_BrepFace.htm">Rhino.Geometry<span id="LSTAAD75C6C_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTAAD75C6C_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>BrepFace</a><br /><p style="color: #dc143c; font-size: 8.5pt; font-weight: bold;">[Missing &lt;param name="face"/&gt; documentation for "M:Rhino.Geometry.Collections.BrepLoopList.Add(Rhino.Geometry.BrepLoopType,Rhino.Geometry.BrepFace)"]</p></dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="T_Rhino_Geometry_BrepLoop.htm">BrepLoop</a><br />New loop that needs to be filled in</div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Collections_BrepLoopList.htm">BrepLoopList Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Geometry_Collections_BrepLoopList_Add.htm">Add Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry_Collections.htm">Rhino.Geometry.Collections Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 10 March 2016 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>