<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Determine Normal Direction of Brep Face</title>
  <meta name="description" content="```cspartial class Examples{  public static Result DetermineNormalDirectionOfBrepFace(RhinoDoc doc)  {    // select a surface    var gs = new GetObject();   ...">

  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/github.min.css">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/vbnet.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <!-- Overridden theme -->
  <link rel="stylesheet" href="/developer-rhino3d-com-branches/wip/css/main.css">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <!-- Bootstrap override -->
  <link rel="stylesheet" href="/developer-rhino3d-com-branches/wip/css/bootstrap-override.css">

  <link rel="canonical" href="http://mcneel.github.io/developer-rhino3d-com-branches/developer-rhino3d-com-branches/wip/samples/rhinocommon/determinenormaldirectionofbrepface/">
  <link rel="alternate" type="application/rss+xml" title="Rhino Developer Docs" href="http://mcneel.github.io/developer-rhino3d-com-branches/developer-rhino3d-com-branches/wip/feed.xml" />

  <link rel="shortcut icon" href="http://developer.rhino3d.com/favicon.ico?v=2" />
  <!-- Saving bookmarks to mobile devices -->
  <!-- For non-Retina (@1× display) iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-precomposed.png"><!-- 57×57px -->
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-72x72-precomposed.png">
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-76x76-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-114x114-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-120x120-precomposed.png">
  <!-- For iPad with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-144x144-precomposed.png">
  <!-- For iPad with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-152x152-precomposed.png">
  <!-- For iPhone 6 Plus with @3× display: -->
  <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/developer-rhino3d-com-branches/wip/images/apple-touch-icon-180x180-precomposed.png">
  <!-- For Chrome for Android: -->
  <link rel="icon" sizes="192x192" href="images/touch-icon-192x192.png">

</head>


  <body>

    <!-- Google Tag Manager **This belongs right after the <body> tag**-->
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MWMDKN"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MWMDKN');
    </script>
    <!-- End Google Tag Manager -->


    <div class="container">
      
<div class="version-banner">
  Hey, you're viewing the <strong>wip</strong> version of this page!
  Click <a href="/developer-rhino3d-com-branches/samples/rhinocommon/determinenormaldirectionofbrepface/">here</a> to view the current (stable) version.
</div>



      <header class="site-header">


    <a class="site-title" href="/developer-rhino3d-com-branches/wip/"><img src="/developer-rhino3d-com-branches/wip/images/rhinodevlogo148x128.png" alt="Rhino Developer Docs" height="48" width="56"></a><a class="site-title" href="/developer-rhino3d-com-branches/wip/">Rhino Developer Docs</a>

    <nav class="site-nav">
      <img class="menu-icon" src="/developer-rhino3d-com-branches/wip/images/gi.svg">
      
      <div class="trigger">
      	<!--<a class="page-link" href="/developer-rhino3d-com-branches/wip/">Welcome</a>-->
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/wip/guides/">Guides</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/wip/api/">API</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/wip/samples/">Samples</a>
              
            
          
        
          
            
          
        
        <a class="page-link" href="http://discourse.mcneel.com/c/rhino-developer">Forums</a>
        <!-- Google Search Engine -->
        <!-- TODO Move to this site back into the Mcneel search, or use a simple site only search for results -->
        <div id="sitesearch">
            <!-- Google CSE Search Box Begins  -->
            <!-- Use of this code assumes agreement with the Google Custom Search Terms of Service. -->
            <!-- The terms of service are available at https://www.google.com/cse/docs/tos.html -->
            <form id="cref" action="/developer-rhino3d-com-branches/wip/search-results.html">
                <input type="hidden" name="cref" value="007988927381198593803:mcq6pshqsn8" />
                <input id="searchtext" type="text" name="q" size="24" value="" placeholder="search" />
                <input class="searchBox" type="submit" name="sa" size="2" value=" " />
            </form>
        <!-- Google CSE Search Box Ends -->
        </div>
        <!--End of Google Search Engine -->
      </div>
    </nav>

</header>


      <div class="page-content">
        <!--div class="wrapper"-->
          <h3>Determine Normal Direction of Brep Face</h3>

<p></p>

<ul class="nav nav-pills">
  <li class="active"><a href="#cs" data-toggle="pill">C#</a></li>
  <li><a href="#vb" data-toggle="pill">VB.NET</a></li>
  <li><a href="#py" data-toggle="pill">Python</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active highlighter-rouge" id="cs"><pre class="highlight"><code><span class="k">partial</span> <span class="k">class</span> <span class="nc">Examples</span>
<span class="p">{</span>
  <span class="k">public</span> <span class="k">static</span> <span class="n">Result</span> <span class="nf">DetermineNormalDirectionOfBrepFace</span><span class="p">(</span><span class="n">RhinoDoc</span> <span class="n">doc</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="c1">// select a surface
</span>    <span class="n">var</span> <span class="n">gs</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">GetObject</span><span class="p">();</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"select surface"</span><span class="p">);</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">GeometryFilter</span> <span class="p">=</span> <span class="n">ObjectType</span><span class="p">.</span><span class="n">Surface</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">DisablePreSelect</span><span class="p">();</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">SubObjectSelect</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gs</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gs</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>
    <span class="c1">// get the selected face
</span>    <span class="n">var</span> <span class="n">face</span> <span class="p">=</span> <span class="n">gs</span><span class="p">.</span><span class="nf">Object</span><span class="p">(</span><span class="m">0</span><span class="p">).</span><span class="nf">Face</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">face</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>

    <span class="c1">// pick a point on the surface.  Constain
</span>    <span class="c1">// picking to the face.
</span>    <span class="n">var</span> <span class="n">gp</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">GetPoint</span><span class="p">();</span>
    <span class="n">gp</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"select point on surface"</span><span class="p">);</span>
    <span class="n">gp</span><span class="p">.</span><span class="nf">Constrain</span><span class="p">(</span><span class="n">face</span><span class="p">,</span> <span class="k">false</span><span class="p">);</span>
    <span class="n">gp</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gp</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gp</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>

    <span class="c1">// get the parameters of the point on the
</span>    <span class="c1">// surface that is clesest to gp.Point()
</span>    <span class="kt">double</span> <span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">;</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">face</span><span class="p">.</span><span class="nf">ClosestPoint</span><span class="p">(</span><span class="n">gp</span><span class="p">.</span><span class="nf">Point</span><span class="p">(),</span> <span class="k">out</span> <span class="n">u</span><span class="p">,</span> <span class="k">out</span> <span class="n">v</span><span class="p">))</span>
    <span class="p">{</span>
      <span class="n">var</span> <span class="n">direction</span> <span class="p">=</span> <span class="n">face</span><span class="p">.</span><span class="nf">NormalAt</span><span class="p">(</span><span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">);</span>
      <span class="k">if</span> <span class="p">(</span><span class="n">face</span><span class="p">.</span><span class="n">OrientationIsReversed</span><span class="p">)</span>
        <span class="n">direction</span><span class="p">.</span><span class="nf">Reverse</span><span class="p">();</span>
      <span class="n">RhinoApp</span><span class="p">.</span><span class="nf">WriteLine</span><span class="p">(</span>
        <span class="kt">string</span><span class="p">.</span><span class="nf">Format</span><span class="p">(</span>
          <span class="s">"Surface normal at uv({0:f},{1:f}) = ({2:f},{3:f},{4:f})"</span><span class="p">,</span>
          <span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">,</span> <span class="n">direction</span><span class="p">.</span><span class="n">X</span><span class="p">,</span> <span class="n">direction</span><span class="p">.</span><span class="n">Y</span><span class="p">,</span> <span class="n">direction</span><span class="p">.</span><span class="n">Z</span><span class="p">));</span>
    <span class="p">}</span>
    <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
</div>

<pre class="tab-pane fade in" id="vb"><code class="language-vbnet">Partial Friend Class Examples
  Public Shared Function DetermineNormalDirectionOfBrepFace(ByVal doc As RhinoDoc) As Result
	' select a surface
	Dim gs = New GetObject()
	gs.SetCommandPrompt("select surface")
	gs.GeometryFilter = ObjectType.Surface
	gs.DisablePreSelect()
	gs.SubObjectSelect = False
	gs.Get()
	If gs.CommandResult() &lt;&gt; Result.Success Then
	  Return gs.CommandResult()
	End If
	' get the selected face
	Dim face = gs.Object(0).Face()
	If face Is Nothing Then
	  Return Result.Failure
	End If

	' pick a point on the surface.  Constain
	' picking to the face.
	Dim gp = New GetPoint()
	gp.SetCommandPrompt("select point on surface")
	gp.Constrain(face, False)
	gp.Get()
	If gp.CommandResult() &lt;&gt; Result.Success Then
	  Return gp.CommandResult()
	End If

	' get the parameters of the point on the
	' surface that is clesest to gp.Point()
	Dim u As Double = Nothing, v As Double = Nothing
	If face.ClosestPoint(gp.Point(), u, v) Then
	  Dim direction = face.NormalAt(u, v)
	  If face.OrientationIsReversed Then
		direction.Reverse()
	  End If
	  RhinoApp.WriteLine(String.Format("Surface normal at uv({0:f},{1:f}) = ({2:f},{3:f},{4:f})", u, v, direction.X, direction.Y, direction.Z))
	End If
	Return Result.Success
  End Function
End Class
</code></pre>

<div class="tab-pane fade in highlighter-rouge" id="py"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">rhinoscriptsyntax</span> <span class="kn">as</span> <span class="nn">rs</span>
<span class="kn">from</span> <span class="nn">scriptcontext</span> <span class="kn">import</span> <span class="o">*</span>
<span class="kn">import</span> <span class="nn">Rhino</span>
<span class="kn">from</span> <span class="nn">Rhino.Commands</span> <span class="kn">import</span> <span class="n">Result</span>

<span class="k">def</span> <span class="nf">RunCommand</span><span class="p">():</span>
  <span class="c"># select a surface</span>
  <span class="n">gs</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Input</span><span class="o">.</span><span class="n">Custom</span><span class="o">.</span><span class="n">GetObject</span><span class="p">()</span>
  <span class="n">gs</span><span class="o">.</span><span class="n">SetCommandPrompt</span><span class="p">(</span><span class="s">"select surface"</span><span class="p">)</span>
  <span class="n">gs</span><span class="o">.</span><span class="n">GeometryFilter</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">DocObjects</span><span class="o">.</span><span class="n">ObjectType</span><span class="o">.</span><span class="n">Surface</span>
  <span class="n">gs</span><span class="o">.</span><span class="n">DisablePreSelect</span><span class="p">()</span>
  <span class="n">gs</span><span class="o">.</span><span class="n">SubObjectSelect</span> <span class="o">=</span> <span class="bp">False</span>
  <span class="n">gs</span><span class="o">.</span><span class="n">Get</span><span class="p">()</span>
  <span class="k">if</span> <span class="n">gs</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span> <span class="o">!=</span> <span class="n">Result</span><span class="o">.</span><span class="n">Success</span><span class="p">:</span>
    <span class="k">return</span> <span class="n">gs</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span>

  <span class="c"># get the selected face</span>
  <span class="n">face</span> <span class="o">=</span> <span class="n">gs</span><span class="o">.</span><span class="n">Object</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span><span class="o">.</span><span class="n">Face</span><span class="p">()</span>
  <span class="k">if</span> <span class="n">face</span> <span class="o">==</span> <span class="bp">None</span><span class="p">:</span>
    <span class="k">return</span>

  <span class="c"># pick a point on the surface.  Constain</span>
  <span class="c"># picking to the face.</span>
  <span class="n">gp</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Input</span><span class="o">.</span><span class="n">Custom</span><span class="o">.</span><span class="n">GetPoint</span><span class="p">()</span>
  <span class="n">gp</span><span class="o">.</span><span class="n">SetCommandPrompt</span><span class="p">(</span><span class="s">"select point on surface"</span><span class="p">)</span>
  <span class="n">gp</span><span class="o">.</span><span class="n">Constrain</span><span class="p">(</span><span class="n">face</span><span class="p">,</span> <span class="bp">False</span><span class="p">)</span>
  <span class="n">gp</span><span class="o">.</span><span class="n">Get</span><span class="p">()</span>
  <span class="k">if</span> <span class="n">gp</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span> <span class="o">!=</span> <span class="n">Result</span><span class="o">.</span><span class="n">Success</span><span class="p">:</span>
    <span class="k">return</span> <span class="n">gp</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span>

  <span class="c"># get the parameters of the point on the</span>
  <span class="c"># surface that is clesest to gp.Point()</span>
  <span class="n">b</span><span class="p">,</span> <span class="n">u</span><span class="p">,</span> <span class="n">v</span> <span class="o">=</span> <span class="n">face</span><span class="o">.</span><span class="n">ClosestPoint</span><span class="p">(</span><span class="n">gp</span><span class="o">.</span><span class="n">Point</span><span class="p">())</span>
  <span class="k">if</span> <span class="n">b</span><span class="p">:</span>
    <span class="nb">dir</span> <span class="o">=</span> <span class="n">face</span><span class="o">.</span><span class="n">NormalAt</span><span class="p">(</span><span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">)</span>
    <span class="k">if</span> <span class="n">face</span><span class="o">.</span><span class="n">OrientationIsReversed</span><span class="p">:</span>
      <span class="nb">dir</span><span class="o">.</span><span class="n">Reverse</span><span class="p">()</span>
    <span class="k">print</span> <span class="s">"Surface normal at uv({0:f},{1:f}) = ({2:f},{3:f},{4:f})"</span><span class="o">.</span><span class="n">format</span><span class="p">(</span>
        <span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">,</span> <span class="nb">dir</span><span class="o">.</span><span class="n">X</span><span class="p">,</span> <span class="nb">dir</span><span class="o">.</span><span class="n">Y</span><span class="p">,</span> <span class="nb">dir</span><span class="o">.</span><span class="n">Z</span><span class="p">)</span>

<span class="k">if</span> <span class="n">__name__</span> <span class="o">==</span> <span class="s">"__main__"</span><span class="p">:</span>
  <span class="n">RunCommand</span><span class="p">()</span>
</code></pre>
</div>

</div>

        <!--/div-->
      </div>

      <footer class="site-footer">

  <div class="wrapper">

    <div class="footer-col-wrapper">

      

        <div class="row">
          <div class="col-md-3">
              <span class="icon  icon--github">
                <svg viewBox="0 0 16 16">
                  <path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/>
                </svg>
              </span>
              <a href="https://github.com/mcneel/developer-rhino3d-com-branches/blob/wip/_samples/rhinocommon/determinenormaldirectionofbrepface.md" target="_blank">Edit on GitHub</a>
          </div>

          <div class="col-md-6 text-center">
            © 1997 - 2016 Robert McNeel &amp; Associates
          </div>

          <div class="col-md-3">
            <span class="pull-right">
              <span class="glyphicon glyphicon-cog"></span>&nbsp;<a href="/developer-rhino3d-com-branches/wip/admin">Admin</a>
            </span>
          </div>

        </div>

      

    </div>

  </div>

  <script>
    if (navigator.appVersion.indexOf("Win")!=-1)
    {
      var body = document.getElementsByTagName("body");
      body[0].style.fontWeight = '400';
    }
  </script>

</footer>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- MathJax -->
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    <script type="text/javascript">
    $('body').scrollspy({
        target: '.bs-docs-sidebar',
        offset: 150 /* fixed header is about 40px high */
    });
    </script>
  </body>

</html>
