<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Point2d.DistanceTo Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="DistanceTo method" /><meta name="System.Keywords" content="Point2d.DistanceTo method" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.Point2d.DistanceTo" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Point2d.DistanceTo(Rhino.Geometry.Point2d)" /><meta name="Description" content="Computes the distance between two points." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry" /><meta name="file" content="M_Rhino_Geometry_Point2d_DistanceTo" /><meta name="guid" content="M_Rhino_Geometry_Point2d_DistanceTo" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_Geometry.htm" title="Rhino.Geometry" tocid="N_Rhino_Geometry">Rhino.Geometry</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_Geometry_Point2d.htm" title="Point2d Structure" tocid="T_Rhino_Geometry_Point2d">Point2d Structure</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Methods_T_Rhino_Geometry_Point2d.htm" title="Point2d Methods" tocid="Methods_T_Rhino_Geometry_Point2d">Point2d Methods</a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Point2d_Add.htm" title="Add Method " tocid="Overload_Rhino_Geometry_Point2d_Add">Add Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Point2d_CompareTo.htm" title="CompareTo Method " tocid="M_Rhino_Geometry_Point2d_CompareTo">CompareTo Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Point2d_DistanceTo.htm" title="DistanceTo Method " tocid="M_Rhino_Geometry_Point2d_DistanceTo">DistanceTo Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Point2d_Divide.htm" title="Divide Method " tocid="M_Rhino_Geometry_Point2d_Divide">Divide Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Point2d_EpsilonEquals.htm" title="EpsilonEquals Method " tocid="M_Rhino_Geometry_Point2d_EpsilonEquals">EpsilonEquals Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Point2d_Equals.htm" title="Equals Method " tocid="Overload_Rhino_Geometry_Point2d_Equals">Equals Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Point2d_GetHashCode.htm" title="GetHashCode Method " tocid="M_Rhino_Geometry_Point2d_GetHashCode">GetHashCode Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Point2d_Multiply.htm" title="Multiply Method " tocid="Overload_Rhino_Geometry_Point2d_Multiply">Multiply Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Point2d_Subtract.htm" title="Subtract Method " tocid="Overload_Rhino_Geometry_Point2d_Subtract">Subtract Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Point2d_ToString.htm" title="ToString Method " tocid="M_Rhino_Geometry_Point2d_ToString">ToString Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Point2d_Transform.htm" title="Transform Method " tocid="M_Rhino_Geometry_Point2d_Transform">Transform Method </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">Point2d<span id="LSTF1D08D64_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTF1D08D64_0?cpp=::|nu=.");</script>DistanceTo Method </td></tr></table><span class="introStyle">Rhino for Mac 5.1</span><div class="summary">
            Computes the distance between two points.
            </div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_Geometry.htm">Rhino.Geometry</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.50000.0 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">double</span> <span class="identifier">DistanceTo</span>(
	<span class="identifier">Point2d</span> <span class="parameter">other</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">DistanceTo</span> ( 
	<span class="parameter">other</span> <span class="keyword">As</span> <span class="identifier">Point2d</span>
) <span class="keyword">As</span> <span class="identifier">Double</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">other</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point2d.htm">Rhino.Geometry<span id="LSTF1D08D64_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTF1D08D64_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point2d</a><br />Another point.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a><br />The length of the line between the two points, or 0 if either point is invalid.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> Rhino;
<span class="highlight-keyword">using</span> Rhino.Geometry;
<span class="highlight-keyword">using</span> Rhino.Commands;
<span class="highlight-keyword">using</span> System.Collections.Generic;
<span class="highlight-keyword">using</span> System.Linq;

<span class="highlight-keyword">namespace</span> examples_cs
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">class</span> LeaderCommand : Command
  {
    <span class="highlight-keyword">public</span> <span class="highlight-keyword">override</span> <span class="highlight-keyword">string</span> EnglishName { <span class="highlight-keyword">get</span> { <span class="highlight-keyword">return</span> <span class="highlight-literal">"csLeader"</span>; } }

    <span class="highlight-keyword">protected</span> <span class="highlight-keyword">override</span> Result RunCommand(RhinoDoc doc, RunMode mode)
    {
      <span class="highlight-keyword">var</span> points = <span class="highlight-keyword">new</span> Point3d[]
      {
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">1</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>),
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>),
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>),
        <span class="highlight-keyword">new</span> Point3d(<span class="highlight-number">9</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>)
      };

      <span class="highlight-keyword">var</span> xy_plane = Plane.WorldXY;

      <span class="highlight-keyword">var</span> points2d = <span class="highlight-keyword">new</span> List&lt;Point2d&gt;();
      <span class="highlight-keyword">foreach</span> (<span class="highlight-keyword">var</span> point3d <span class="highlight-keyword">in</span> points)
      {
        <span class="highlight-keyword">double</span> x, y;
        <span class="highlight-keyword">if</span> (xy_plane.ClosestParameter(point3d, <span class="highlight-keyword">out</span> x, <span class="highlight-keyword">out</span> y))
        {
          <span class="highlight-keyword">var</span> point2d = <span class="highlight-keyword">new</span> Point2d(x, y);
          <span class="highlight-keyword">if</span> (points2d.Count &lt; <span class="highlight-number">1</span> || point2d.DistanceTo(points2d.Last&lt;Point2d&gt;()) &gt; RhinoMath.SqrtEpsilon)
            points2d.Add(point2d);
        }
      }

      doc.Objects.AddLeader(xy_plane, points2d);
      doc.Views.Redraw();
      <span class="highlight-keyword">return</span> Result.Success;
    }
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Imports</span> Rhino
<span class="highlight-keyword">Imports</span> Rhino.Geometry
<span class="highlight-keyword">Imports</span> Rhino.Commands
<span class="highlight-keyword">Imports</span> System.Collections.Generic
<span class="highlight-keyword">Imports</span> System.Linq

<span class="highlight-keyword">Namespace</span> examples_vb
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Class</span> LeaderCommand
    <span class="highlight-keyword">Inherits</span> Command
    <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">ReadOnly</span> <span class="highlight-keyword">Property</span> EnglishName() <span class="highlight-keyword">As</span> <span class="highlight-keyword">String</span>
      <span class="highlight-keyword">Get</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-literal">"vbLeader"</span>
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">Get</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Property</span>

    <span class="highlight-keyword">Protected</span> <span class="highlight-keyword">Overrides</span> <span class="highlight-keyword">Function</span> RunCommand(doc <span class="highlight-keyword">As</span> RhinoDoc, mode <span class="highlight-keyword">As</span> RunMode) <span class="highlight-keyword">As</span> Result
      <span class="highlight-keyword">Dim</span> points = <span class="highlight-keyword">New</span> List(<span class="highlight-keyword">Of</span> Point3d)() From { _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">1</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">1</span>, <span class="highlight-number">0</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">5</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>), _
        <span class="highlight-keyword">New</span> Point3d(<span class="highlight-number">9</span>, <span class="highlight-number">5</span>, <span class="highlight-number">0</span>) _
      }

      <span class="highlight-keyword">Dim</span> xyPlane = Plane.WorldXY

      <span class="highlight-keyword">Dim</span> points2d = <span class="highlight-keyword">New</span> List(<span class="highlight-keyword">Of</span> Point2d)()
      <span class="highlight-keyword">For</span> <span class="highlight-keyword">Each</span> point3d <span class="highlight-keyword">As</span> Point3d <span class="highlight-keyword">In</span> points
        <span class="highlight-keyword">Dim</span> x <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span>, y <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span>
        <span class="highlight-keyword">If</span> xyPlane.ClosestParameter(point3d, x, y) <span class="highlight-keyword">Then</span>
          <span class="highlight-keyword">Dim</span> point2d = <span class="highlight-keyword">New</span> Point2d(x, y)
          <span class="highlight-keyword">If</span> points2d.Count &lt; <span class="highlight-number">1</span> <span class="highlight-keyword">OrElse</span> point2d.DistanceTo(points2d.Last()) &gt; RhinoMath.SqrtEpsilon <span class="highlight-keyword">Then</span>
            points2d.Add(point2d)
          <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
        <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Next</span>

      doc.Objects.AddLeader(xyPlane, points2d)
      doc.Views.Redraw()
      <span class="highlight-keyword">Return</span> Result.Success
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Namespace</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> rhinoscriptsyntax <span class="highlight-keyword">as</span> rs

<span class="highlight-keyword">def</span> RunCommand():
  points = [(<span class="highlight-number">1</span>,<span class="highlight-number">1</span>,<span class="highlight-number">0</span>), (<span class="highlight-number">5</span>,<span class="highlight-number">1</span>,<span class="highlight-number">0</span>), (<span class="highlight-number">5</span>,<span class="highlight-number">5</span>,<span class="highlight-number">0</span>), (<span class="highlight-number">9</span>,<span class="highlight-number">5</span>,<span class="highlight-number">0</span>)]
  rs.AddLeader(points)

<span class="highlight-keyword">if</span> __name__ == <span class="highlight-literal">"__main__"</span>:
    RunCommand()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Point2d.htm">Point2d Structure</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry.htm">Rhino.Geometry Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 4 October 2015 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>