<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>BendSpaceMorph Constructor (Point3d, Point3d, Point3d, Double, Boolean, Boolean)</title><meta name="Language" content="en-us" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Morphs.BendSpaceMorph.#ctor(Rhino.Geometry.Point3d,Rhino.Geometry.Point3d,Rhino.Geometry.Point3d,System.Double,System.Boolean,System.Boolean)" /><meta name="Description" content="Constructs a bend space morph." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry.Morphs" /><meta name="file" content="M_Rhino_Geometry_Morphs_BendSpaceMorph__ctor_1" /><meta name="guid" content="M_Rhino_Geometry_Morphs_BendSpaceMorph__ctor_1" /><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="N_Rhino_Geometry_Morphs.htm" title="Rhino.Geometry.Morphs" tocid="N_Rhino_Geometry_Morphs">Rhino.Geometry.Morphs</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="T_Rhino_Geometry_Morphs_BendSpaceMorph.htm" title="BendSpaceMorph Class" tocid="T_Rhino_Geometry_Morphs_BendSpaceMorph">BendSpaceMorph Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="Overload_Rhino_Geometry_Morphs_BendSpaceMorph__ctor.htm" title="BendSpaceMorph Constructor " tocid="Overload_Rhino_Geometry_Morphs_BendSpaceMorph__ctor">BendSpaceMorph Constructor </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Morphs_BendSpaceMorph__ctor.htm" title="BendSpaceMorph Constructor (Point3d, Point3d, Point3d, Boolean, Boolean)" tocid="M_Rhino_Geometry_Morphs_BendSpaceMorph__ctor">BendSpaceMorph Constructor (Point3d, Point3d, Point3d, Boolean, Boolean)</a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="M_Rhino_Geometry_Morphs_BendSpaceMorph__ctor_1.htm" title="BendSpaceMorph Constructor (Point3d, Point3d, Point3d, Double, Boolean, Boolean)" tocid="M_Rhino_Geometry_Morphs_BendSpaceMorph__ctor_1">BendSpaceMorph Constructor (Point3d, Point3d, Point3d, Double, Boolean, Boolean)</a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">BendSpaceMorph Constructor (Point3d, Point3d, Point3d, Double, Boolean, Boolean)</td></tr></table><span class="introStyle">Rhino 5 for Windows</span><div class="summary">
            Constructs a bend space morph.
            </div><p> </p><strong>Namespace:</strong> <a href="N_Rhino_Geometry_Morphs.htm">Rhino.Geometry.Morphs</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.30000.16 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">BendSpaceMorph</span>(
	<span class="identifier">Point3d</span> <span class="parameter">start</span>,
	<span class="identifier">Point3d</span> <span class="parameter">end</span>,
	<span class="identifier">Point3d</span> <span class="parameter">point</span>,
	<span class="identifier">double</span> <span class="parameter">angle</span>,
	<span class="identifier">bool</span> <span class="parameter">straight</span>,
	<span class="identifier">bool</span> <span class="parameter">symmetric</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Sub</span> <span class="identifier">New</span> ( 
	<span class="parameter">start</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>,
	<span class="parameter">end</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>,
	<span class="parameter">point</span> <span class="keyword">As</span> <span class="identifier">Point3d</span>,
	<span class="parameter">angle</span> <span class="keyword">As</span> <span class="identifier">Double</span>,
	<span class="parameter">straight</span> <span class="keyword">As</span> <span class="identifier">Boolean</span>,
	<span class="parameter">symmetric</span> <span class="keyword">As</span> <span class="identifier">Boolean</span>
)</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">start</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LST844EA8CC_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST844EA8CC_0?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />Start of spine that represents the original orientation of the object.</dd><dt><span class="parameter">end</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LST844EA8CC_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST844EA8CC_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />End of spine.</dd><dt><span class="parameter">point</span></dt><dd>Type: <a href="T_Rhino_Geometry_Point3d.htm">Rhino.Geometry<span id="LST844EA8CC_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST844EA8CC_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Point3d</a><br />Used for bend direction.</dd><dt><span class="parameter">angle</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span id="LST844EA8CC_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST844EA8CC_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />Bend angle in radians.</dd><dt><span class="parameter">straight</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">System<span id="LST844EA8CC_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST844EA8CC_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Boolean</a><br />If false, then point determines the region to bend. If true, only the spine region is bent.</dd><dt><span class="parameter">symmetric</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">System<span id="LST844EA8CC_5"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST844EA8CC_5?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Boolean</a><br />If false, then only one end of the object bends. If true, then the object will bend symmetrically around the center if you start the spine in the middle of the object.</dd></dl></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID2RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="T_Rhino_Geometry_Morphs_BendSpaceMorph.htm">BendSpaceMorph Class</a></div><div class="seeAlsoStyle"><a href="Overload_Rhino_Geometry_Morphs_BendSpaceMorph__ctor.htm">BendSpaceMorph Overload</a></div><div class="seeAlsoStyle"><a href="N_Rhino_Geometry_Morphs.htm">Rhino.Geometry.Morphs Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 10 March 2016 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>