<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Orient On Surface</title>
  <meta name="description" content="```cspartial class Examples{  public static Rhino.Commands.Result OrientOnSrf(Rhino.RhinoDoc doc)  {    // Select objects to orient    Rhino.Input.Custom.Get...">

  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/github.min.css">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/vbnet.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <!-- Overridden theme -->
  <link rel="stylesheet" href="/developer-rhino3d-com-branches/rebase/css/main.css">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <!-- Bootstrap override -->
  <link rel="stylesheet" href="/developer-rhino3d-com-branches/rebase/css/bootstrap-override.css">

  <link rel="canonical" href="http://mcneel.github.io/developer-rhino3d-com-branches/developer-rhino3d-com-branches/rebase/samples/rhinocommon/orientonsrf/">
  <link rel="alternate" type="application/rss+xml" title="Rhino Developer Docs" href="http://mcneel.github.io/developer-rhino3d-com-branches/developer-rhino3d-com-branches/rebase/feed.xml" />

  <link rel="shortcut icon" href="http://developer.rhino3d.com/favicon.ico?v=2" />
  <!-- Saving bookmarks to mobile devices -->
  <!-- For non-Retina (@1× display) iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-precomposed.png"><!-- 57×57px -->
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-72x72-precomposed.png">
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-76x76-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-114x114-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-120x120-precomposed.png">
  <!-- For iPad with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-144x144-precomposed.png">
  <!-- For iPad with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-152x152-precomposed.png">
  <!-- For iPhone 6 Plus with @3× display: -->
  <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-180x180-precomposed.png">
  <!-- For Chrome for Android: -->
  <link rel="icon" sizes="192x192" href="images/touch-icon-192x192.png">

</head>


  <body>

    <!-- Google Tag Manager **This belongs right after the <body> tag**-->
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MWMDKN"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MWMDKN');
    </script>
    <!-- End Google Tag Manager -->


    <div class="container">
      
<div class="version-banner">
  Hey, you're viewing the <strong>rebase</strong> version of this page!
  Click <a href="/developer-rhino3d-com-branches/samples/rhinocommon/orientonsrf/">here</a> to view the current (stable) version.
</div>



      <header class="site-header">


    <a class="site-title" href="/developer-rhino3d-com-branches/rebase/"><img src="/developer-rhino3d-com-branches/rebase/images/rhinodevlogo148x128.png" alt="Rhino Developer Docs" height="48" width="56"></a><a class="site-title" href="/developer-rhino3d-com-branches/rebase/">Rhino Developer Docs</a>

    <nav class="site-nav">
      <img class="menu-icon" src="/developer-rhino3d-com-branches/rebase/images/gi.svg">
      
      <div class="trigger">
      	<!--<a class="page-link" href="/developer-rhino3d-com-branches/rebase/">Welcome</a>-->
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/rebase/guides/">Guides</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/rebase/api/">API</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/rebase/samples/">Samples</a>
              
            
          
        
          
            
          
        
        <a class="page-link" href="http://discourse.mcneel.com/c/rhino-developer">Forums</a>
        <!-- Google Search Engine -->
        <!-- TODO Move to this site back into the Mcneel search, or use a simple site only search for results -->
        <div id="sitesearch">
            <!-- Google CSE Search Box Begins  -->
            <!-- Use of this code assumes agreement with the Google Custom Search Terms of Service. -->
            <!-- The terms of service are available at https://www.google.com/cse/docs/tos.html -->
            <form id="cref" action="/developer-rhino3d-com-branches/rebase/search-results.html">
                <input type="hidden" name="cref" value="007988927381198593803:mcq6pshqsn8" />
                <input id="searchtext" type="text" name="q" size="24" value="" placeholder="search" />
                <input class="searchBox" type="submit" name="sa" size="2" value=" " />
            </form>
        <!-- Google CSE Search Box Ends -->
        </div>
        <!--End of Google Search Engine -->
      </div>
    </nav>

</header>


      <div class="page-content">
        <!--div class="wrapper"-->
          <h3>Orient On Surface</h3>

<p></p>

<ul class="nav nav-pills">
  <li class="active"><a href="#cs" data-toggle="pill">C#</a></li>
  <li><a href="#vb" data-toggle="pill">VB.NET</a></li>
  <li><a href="#py" data-toggle="pill">Python</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active highlighter-rouge" id="cs"><pre class="highlight"><code><span class="k">partial</span> <span class="k">class</span> <span class="nc">Examples</span>
<span class="p">{</span>
  <span class="k">public</span> <span class="k">static</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span> <span class="nf">OrientOnSrf</span><span class="p">(</span><span class="n">Rhino</span><span class="p">.</span><span class="n">RhinoDoc</span> <span class="n">doc</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="c1">// Select objects to orient
</span>    <span class="n">Rhino</span><span class="p">.</span><span class="n">Input</span><span class="p">.</span><span class="n">Custom</span><span class="p">.</span><span class="n">GetObject</span> <span class="n">go</span> <span class="p">=</span> <span class="k">new</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Input</span><span class="p">.</span><span class="n">Custom</span><span class="p">.</span><span class="nf">GetObject</span><span class="p">();</span>
    <span class="n">go</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"Select objects to orient"</span><span class="p">);</span>
    <span class="n">go</span><span class="p">.</span><span class="n">SubObjectSelect</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">go</span><span class="p">.</span><span class="n">GroupSelect</span> <span class="p">=</span> <span class="k">true</span><span class="p">;</span>
    <span class="n">go</span><span class="p">.</span><span class="nf">GetMultiple</span><span class="p">(</span><span class="m">1</span><span class="p">,</span> <span class="m">0</span><span class="p">);</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">go</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">go</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>

    <span class="c1">// Point to orient from
</span>    <span class="n">Rhino</span><span class="p">.</span><span class="n">Input</span><span class="p">.</span><span class="n">Custom</span><span class="p">.</span><span class="n">GetPoint</span> <span class="n">gp</span> <span class="p">=</span> <span class="k">new</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Input</span><span class="p">.</span><span class="n">Custom</span><span class="p">.</span><span class="nf">GetPoint</span><span class="p">();</span>
    <span class="n">gp</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"Point to orient from"</span><span class="p">);</span>
    <span class="n">gp</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gp</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gp</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>

    <span class="c1">// Define source plane
</span>    <span class="n">Rhino</span><span class="p">.</span><span class="n">Display</span><span class="p">.</span><span class="n">RhinoView</span> <span class="n">view</span> <span class="p">=</span> <span class="n">gp</span><span class="p">.</span><span class="nf">View</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">view</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
    <span class="p">{</span>
      <span class="n">view</span> <span class="p">=</span> <span class="n">doc</span><span class="p">.</span><span class="n">Views</span><span class="p">.</span><span class="n">ActiveView</span><span class="p">;</span>
      <span class="k">if</span> <span class="p">(</span><span class="n">view</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
        <span class="k">return</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>
    <span class="p">}</span>
    <span class="n">Rhino</span><span class="p">.</span><span class="n">Geometry</span><span class="p">.</span><span class="n">Plane</span> <span class="n">source_plane</span> <span class="p">=</span> <span class="n">view</span><span class="p">.</span><span class="n">ActiveViewport</span><span class="p">.</span><span class="nf">ConstructionPlane</span><span class="p">();</span>
    <span class="n">source_plane</span><span class="p">.</span><span class="n">Origin</span> <span class="p">=</span> <span class="n">gp</span><span class="p">.</span><span class="nf">Point</span><span class="p">();</span>

    <span class="c1">// Surface to orient on
</span>    <span class="n">Rhino</span><span class="p">.</span><span class="n">Input</span><span class="p">.</span><span class="n">Custom</span><span class="p">.</span><span class="n">GetObject</span> <span class="n">gs</span> <span class="p">=</span> <span class="k">new</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Input</span><span class="p">.</span><span class="n">Custom</span><span class="p">.</span><span class="nf">GetObject</span><span class="p">();</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"Surface to orient on"</span><span class="p">);</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">GeometryFilter</span> <span class="p">=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">DocObjects</span><span class="p">.</span><span class="n">ObjectType</span><span class="p">.</span><span class="n">Surface</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">SubObjectSelect</span> <span class="p">=</span> <span class="k">true</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">DeselectAllBeforePostSelect</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">OneByOnePostSelect</span> <span class="p">=</span> <span class="k">true</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gs</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gs</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>

    <span class="n">Rhino</span><span class="p">.</span><span class="n">DocObjects</span><span class="p">.</span><span class="n">ObjRef</span> <span class="n">objref</span> <span class="p">=</span> <span class="n">gs</span><span class="p">.</span><span class="nf">Object</span><span class="p">(</span><span class="m">0</span><span class="p">);</span>
    <span class="c1">// get selected surface object
</span>    <span class="n">Rhino</span><span class="p">.</span><span class="n">DocObjects</span><span class="p">.</span><span class="n">RhinoObject</span> <span class="n">obj</span> <span class="p">=</span> <span class="n">objref</span><span class="p">.</span><span class="nf">Object</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">obj</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>
    <span class="c1">// get selected surface (face)
</span>    <span class="n">Rhino</span><span class="p">.</span><span class="n">Geometry</span><span class="p">.</span><span class="n">Surface</span> <span class="n">surface</span> <span class="p">=</span> <span class="n">objref</span><span class="p">.</span><span class="nf">Surface</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">surface</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>
    <span class="c1">// Unselect surface
</span>    <span class="n">obj</span><span class="p">.</span><span class="nf">Select</span><span class="p">(</span><span class="k">false</span><span class="p">);</span>

    <span class="c1">// Point on surface to orient to
</span>    <span class="n">gp</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"Point on surface to orient to"</span><span class="p">);</span>
    <span class="n">gp</span><span class="p">.</span><span class="nf">Constrain</span><span class="p">(</span><span class="n">surface</span><span class="p">,</span> <span class="k">false</span><span class="p">);</span>
    <span class="n">gp</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gp</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gp</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>

    <span class="c1">// Do transformation
</span>    <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span> <span class="n">rc</span> <span class="p">=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>
    <span class="kt">double</span> <span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">;</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">surface</span><span class="p">.</span><span class="nf">ClosestPoint</span><span class="p">(</span><span class="n">gp</span><span class="p">.</span><span class="nf">Point</span><span class="p">(),</span> <span class="k">out</span> <span class="n">u</span><span class="p">,</span> <span class="k">out</span> <span class="n">v</span><span class="p">))</span>
    <span class="p">{</span>
      <span class="n">Rhino</span><span class="p">.</span><span class="n">Geometry</span><span class="p">.</span><span class="n">Plane</span> <span class="n">target_plane</span><span class="p">;</span>
      <span class="k">if</span> <span class="p">(</span><span class="n">surface</span><span class="p">.</span><span class="nf">FrameAt</span><span class="p">(</span><span class="n">u</span><span class="p">,</span> <span class="n">v</span><span class="p">,</span> <span class="k">out</span> <span class="n">target_plane</span><span class="p">))</span>
      <span class="p">{</span>
        <span class="c1">// Build transformation
</span>        <span class="n">Rhino</span><span class="p">.</span><span class="n">Geometry</span><span class="p">.</span><span class="n">Transform</span> <span class="n">xform</span> <span class="p">=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Geometry</span><span class="p">.</span><span class="n">Transform</span><span class="p">.</span><span class="nf">PlaneToPlane</span><span class="p">(</span><span class="n">source_plane</span><span class="p">,</span> <span class="n">target_plane</span><span class="p">);</span>

        <span class="c1">// Do the transformation. In this example, we will copy the original objects
</span>        <span class="k">const</span> <span class="kt">bool</span> <span class="n">delete_original</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
        <span class="k">for</span> <span class="p">(</span><span class="kt">int</span> <span class="n">i</span> <span class="p">=</span> <span class="m">0</span><span class="p">;</span> <span class="n">i</span> <span class="p">&lt;</span> <span class="n">go</span><span class="p">.</span><span class="n">ObjectCount</span><span class="p">;</span> <span class="n">i</span><span class="p">++)</span>
          <span class="n">doc</span><span class="p">.</span><span class="n">Objects</span><span class="p">.</span><span class="nf">Transform</span><span class="p">(</span><span class="n">go</span><span class="p">.</span><span class="nf">Object</span><span class="p">(</span><span class="n">i</span><span class="p">),</span> <span class="n">xform</span><span class="p">,</span> <span class="n">delete_original</span><span class="p">);</span>

        <span class="n">doc</span><span class="p">.</span><span class="n">Views</span><span class="p">.</span><span class="nf">Redraw</span><span class="p">();</span>
        <span class="n">rc</span> <span class="p">=</span> <span class="n">Rhino</span><span class="p">.</span><span class="n">Commands</span><span class="p">.</span><span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">;</span>
      <span class="p">}</span>
    <span class="p">}</span>
    <span class="k">return</span> <span class="n">rc</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
</div>

<pre class="tab-pane fade in" id="vb"><code class="language-vbnet">Partial Friend Class Examples
  Public Shared Function OrientOnSrf(ByVal doc As Rhino.RhinoDoc) As Rhino.Commands.Result
	' Select objects to orient
	Dim go As New Rhino.Input.Custom.GetObject()
	go.SetCommandPrompt("Select objects to orient")
	go.SubObjectSelect = False
	go.GroupSelect = True
	go.GetMultiple(1, 0)
	If go.CommandResult() &lt;&gt; Rhino.Commands.Result.Success Then
	  Return go.CommandResult()
	End If

	' Point to orient from
	Dim gp As New Rhino.Input.Custom.GetPoint()
	gp.SetCommandPrompt("Point to orient from")
	gp.Get()
	If gp.CommandResult() &lt;&gt; Rhino.Commands.Result.Success Then
	  Return gp.CommandResult()
	End If

	' Define source plane
	Dim view As Rhino.Display.RhinoView = gp.View()
	If view Is Nothing Then
	  view = doc.Views.ActiveView
	  If view Is Nothing Then
		Return Rhino.Commands.Result.Failure
	  End If
	End If
	Dim source_plane As Rhino.Geometry.Plane = view.ActiveViewport.ConstructionPlane()
	source_plane.Origin = gp.Point()

	' Surface to orient on
	Dim gs As New Rhino.Input.Custom.GetObject()
	gs.SetCommandPrompt("Surface to orient on")
	gs.GeometryFilter = Rhino.DocObjects.ObjectType.Surface
	gs.SubObjectSelect = True
	gs.DeselectAllBeforePostSelect = False
	gs.OneByOnePostSelect = True
	gs.Get()
	If gs.CommandResult() &lt;&gt; Rhino.Commands.Result.Success Then
	  Return gs.CommandResult()
	End If

	Dim objref As Rhino.DocObjects.ObjRef = gs.Object(0)
	' get selected surface object
	Dim obj As Rhino.DocObjects.RhinoObject = objref.Object()
	If obj Is Nothing Then
	  Return Rhino.Commands.Result.Failure
	End If
	' get selected surface (face)
	Dim surface As Rhino.Geometry.Surface = objref.Surface()
	If surface Is Nothing Then
	  Return Rhino.Commands.Result.Failure
	End If
	' Unselect surface
	obj.Select(False)

	' Point on surface to orient to
	gp.SetCommandPrompt("Point on surface to orient to")
	gp.Constrain(surface, False)
	gp.Get()
	If gp.CommandResult() &lt;&gt; Rhino.Commands.Result.Success Then
	  Return gp.CommandResult()
	End If

	' Do transformation
	Dim rc As Rhino.Commands.Result = Rhino.Commands.Result.Failure
	Dim u As Double = Nothing, v As Double = Nothing
	If surface.ClosestPoint(gp.Point(), u, v) Then
	  Dim target_plane As Rhino.Geometry.Plane = Nothing
	  If surface.FrameAt(u, v, target_plane) Then
		' Build transformation
		Dim xform As Rhino.Geometry.Transform = Rhino.Geometry.Transform.PlaneToPlane(source_plane, target_plane)

		' Do the transformation. In this example, we will copy the original objects
		Const delete_original As Boolean = False
		For i As Integer = 0 To go.ObjectCount - 1
		  doc.Objects.Transform(go.Object(i), xform, delete_original)
		Next i

		doc.Views.Redraw()
		rc = Rhino.Commands.Result.Success
	  End If
	End If
	Return rc
  End Function
End Class
</code></pre>

<div class="tab-pane fade in highlighter-rouge" id="py"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">Rhino</span>
<span class="kn">import</span> <span class="nn">scriptcontext</span>
<span class="kn">import</span> <span class="nn">System.Guid</span>

<span class="k">def</span> <span class="nf">OrientOnSrf</span><span class="p">():</span>
    <span class="c"># Select objects to orient</span>
    <span class="n">go</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Input</span><span class="o">.</span><span class="n">Custom</span><span class="o">.</span><span class="n">GetObject</span><span class="p">()</span>
    <span class="n">go</span><span class="o">.</span><span class="n">SetCommandPrompt</span><span class="p">(</span><span class="s">"Select objects to orient"</span><span class="p">)</span>
    <span class="n">go</span><span class="o">.</span><span class="n">SubObjectSelect</span> <span class="o">=</span> <span class="bp">False</span>
    <span class="n">go</span><span class="o">.</span><span class="n">GroupSelect</span> <span class="o">=</span> <span class="bp">True</span>
    <span class="n">go</span><span class="o">.</span><span class="n">GetMultiple</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
    <span class="k">if</span> <span class="n">go</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span><span class="o">!=</span><span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Success</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">go</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span>

    <span class="c"># Point to orient from</span>
    <span class="n">gp</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Input</span><span class="o">.</span><span class="n">Custom</span><span class="o">.</span><span class="n">GetPoint</span><span class="p">()</span>
    <span class="n">gp</span><span class="o">.</span><span class="n">SetCommandPrompt</span><span class="p">(</span><span class="s">"Point to orient from"</span><span class="p">)</span>
    <span class="n">gp</span><span class="o">.</span><span class="n">Get</span><span class="p">()</span>
    <span class="k">if</span> <span class="n">gp</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span><span class="o">!=</span><span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Success</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">gp</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span>

    <span class="c"># Define source plane</span>
    <span class="n">view</span> <span class="o">=</span> <span class="n">gp</span><span class="o">.</span><span class="n">View</span><span class="p">()</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="n">view</span><span class="p">:</span>
        <span class="n">view</span> <span class="o">=</span> <span class="n">doc</span><span class="o">.</span><span class="n">Views</span><span class="o">.</span><span class="n">ActiveView</span>
        <span class="k">if</span> <span class="ow">not</span> <span class="n">view</span><span class="p">:</span> <span class="k">return</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Failure</span>

    <span class="n">source_plane</span> <span class="o">=</span> <span class="n">view</span><span class="o">.</span><span class="n">ActiveViewport</span><span class="o">.</span><span class="n">ConstructionPlane</span><span class="p">()</span>
    <span class="n">source_plane</span><span class="o">.</span><span class="n">Origin</span> <span class="o">=</span> <span class="n">gp</span><span class="o">.</span><span class="n">Point</span><span class="p">()</span>

    <span class="c"># Surface to orient on</span>
    <span class="n">gs</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Input</span><span class="o">.</span><span class="n">Custom</span><span class="o">.</span><span class="n">GetObject</span><span class="p">()</span>
    <span class="n">gs</span><span class="o">.</span><span class="n">SetCommandPrompt</span><span class="p">(</span><span class="s">"Surface to orient on"</span><span class="p">)</span>
    <span class="n">gs</span><span class="o">.</span><span class="n">GeometryFilter</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">DocObjects</span><span class="o">.</span><span class="n">ObjectType</span><span class="o">.</span><span class="n">Surface</span>
    <span class="n">gs</span><span class="o">.</span><span class="n">SubObjectSelect</span> <span class="o">=</span> <span class="bp">True</span>
    <span class="n">gs</span><span class="o">.</span><span class="n">DeselectAllBeforePostSelect</span> <span class="o">=</span> <span class="bp">False</span>
    <span class="n">gs</span><span class="o">.</span><span class="n">OneByOnePostSelect</span> <span class="o">=</span> <span class="bp">True</span>
    <span class="n">gs</span><span class="o">.</span><span class="n">Get</span><span class="p">()</span>
    <span class="k">if</span> <span class="n">gs</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span><span class="o">!=</span><span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Success</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">gs</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span>

    <span class="n">objref</span> <span class="o">=</span> <span class="n">gs</span><span class="o">.</span><span class="n">Object</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
    <span class="c"># get selected surface object</span>
    <span class="n">obj</span> <span class="o">=</span> <span class="n">objref</span><span class="o">.</span><span class="n">Object</span><span class="p">()</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="n">obj</span><span class="p">:</span> <span class="k">return</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Failure</span>
    <span class="c"># get selected surface (face)</span>
    <span class="n">surface</span> <span class="o">=</span> <span class="n">objref</span><span class="o">.</span><span class="n">Surface</span><span class="p">()</span>
    <span class="k">if</span> <span class="ow">not</span> <span class="n">surface</span><span class="p">:</span> <span class="k">return</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Failure</span>
    <span class="c"># Unselect surface</span>
    <span class="n">obj</span><span class="o">.</span><span class="n">Select</span><span class="p">(</span><span class="bp">False</span><span class="p">)</span>

    <span class="c"># Point on surface to orient to</span>
    <span class="n">gp</span><span class="o">.</span><span class="n">SetCommandPrompt</span><span class="p">(</span><span class="s">"Point on surface to orient to"</span><span class="p">)</span>
    <span class="n">gp</span><span class="o">.</span><span class="n">Constrain</span><span class="p">(</span><span class="n">surface</span><span class="p">,</span> <span class="bp">False</span><span class="p">)</span>
    <span class="n">gp</span><span class="o">.</span><span class="n">Get</span><span class="p">()</span>
    <span class="k">if</span> <span class="n">gp</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span><span class="o">!=</span><span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Success</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">gp</span><span class="o">.</span><span class="n">CommandResult</span><span class="p">()</span>

    <span class="c"># Do transformation</span>
    <span class="n">rc</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Failure</span>
    <span class="n">getrc</span><span class="p">,</span> <span class="n">u</span><span class="p">,</span> <span class="n">v</span> <span class="o">=</span> <span class="n">surface</span><span class="o">.</span><span class="n">ClosestPoint</span><span class="p">(</span><span class="n">gp</span><span class="o">.</span><span class="n">Point</span><span class="p">())</span>
    <span class="k">if</span> <span class="n">getrc</span><span class="p">:</span>
        <span class="n">getrc</span><span class="p">,</span> <span class="n">target_plane</span> <span class="o">=</span> <span class="n">surface</span><span class="o">.</span><span class="n">FrameAt</span><span class="p">(</span><span class="n">u</span><span class="p">,</span><span class="n">v</span><span class="p">)</span>
        <span class="k">if</span> <span class="n">getrc</span><span class="p">:</span>
            <span class="c"># Build transformation</span>
            <span class="n">xform</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Geometry</span><span class="o">.</span><span class="n">Transform</span><span class="o">.</span><span class="n">PlaneToPlane</span><span class="p">(</span><span class="n">source_plane</span><span class="p">,</span> <span class="n">target_plane</span><span class="p">)</span>
            <span class="c"># Do the transformation. In this example, we will copy the original objects</span>
            <span class="n">delete_original</span> <span class="o">=</span> <span class="bp">False</span>
            <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">go</span><span class="o">.</span><span class="n">ObjectCount</span><span class="p">):</span>
                <span class="n">rhobj</span> <span class="o">=</span> <span class="n">go</span><span class="o">.</span><span class="n">Object</span><span class="p">(</span><span class="n">i</span><span class="p">)</span>
                <span class="n">scriptcontext</span><span class="o">.</span><span class="n">doc</span><span class="o">.</span><span class="n">Objects</span><span class="o">.</span><span class="n">Transform</span><span class="p">(</span><span class="n">rhobj</span><span class="p">,</span> <span class="n">xform</span><span class="p">,</span> <span class="n">delete_original</span><span class="p">)</span>
            <span class="n">scriptcontext</span><span class="o">.</span><span class="n">doc</span><span class="o">.</span><span class="n">Views</span><span class="o">.</span><span class="n">Redraw</span><span class="p">()</span>
            <span class="n">rc</span> <span class="o">=</span> <span class="n">Rhino</span><span class="o">.</span><span class="n">Commands</span><span class="o">.</span><span class="n">Result</span><span class="o">.</span><span class="n">Success</span>
    <span class="k">return</span> <span class="n">rc</span>


<span class="k">if</span> <span class="n">__name__</span><span class="o">==</span><span class="s">"__main__"</span><span class="p">:</span>
    <span class="n">OrientOnSrf</span><span class="p">()</span>
</code></pre>
</div>

</div>

        <!--/div-->
      </div>

      <footer class="site-footer">

  <div class="wrapper">

    <div class="footer-col-wrapper">

      

        <div class="row">
          <div class="col-md-3">
              <span class="icon  icon--github">
                <svg viewBox="0 0 16 16">
                  <path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/>
                </svg>
              </span>
              <a href="https://github.com/mcneel/developer-rhino3d-com-branches/blob/rebase/_samples/rhinocommon/orientonsrf.md" target="_blank">Edit on GitHub</a>
          </div>

          <div class="col-md-6 text-center">
            © 1997 - 2016 Robert McNeel &amp; Associates
          </div>

          <div class="col-md-3">
            <span class="pull-right">
              <span class="glyphicon glyphicon-cog"></span>&nbsp;<a href="/developer-rhino3d-com-branches/rebase/admin">Admin</a>
            </span>
          </div>

        </div>

      

    </div>

  </div>

  <script>
    if (navigator.appVersion.indexOf("Win")!=-1)
    {
      var body = document.getElementsByTagName("body");
      body[0].style.fontWeight = '400';
    }
  </script>

</footer>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- MathJax -->
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    <script type="text/javascript">
    $('body').scrollspy({
        target: '.bs-docs-sidebar',
        offset: 150 /* fixed header is about 40px high */
    });
    </script>
  </body>

</html>
