<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Determine Furthest Z on Surface given X Y</title>
  <meta name="description" content="```cspartial class Examples{  public static Result FurthestZOnSurfaceGivenXY(RhinoDoc doc)  {    #region user input    // select a surface    var gs = new Ge...">

  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/github.min.css">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.5/languages/vbnet.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

  <!-- Overridden theme -->
  <link rel="stylesheet" href="/developer-rhino3d-com-branches/rebase/css/main.css">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <!-- Bootstrap override -->
  <link rel="stylesheet" href="/developer-rhino3d-com-branches/rebase/css/bootstrap-override.css">

  <link rel="canonical" href="http://mcneel.github.io/developer-rhino3d-com-branches/developer-rhino3d-com-branches/rebase/samples/rhinocommon/furthestzonsurfacegivenxy/">
  <link rel="alternate" type="application/rss+xml" title="Rhino Developer Docs" href="http://mcneel.github.io/developer-rhino3d-com-branches/developer-rhino3d-com-branches/rebase/feed.xml" />

  <link rel="shortcut icon" href="http://developer.rhino3d.com/favicon.ico?v=2" />
  <!-- Saving bookmarks to mobile devices -->
  <!-- For non-Retina (@1× display) iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-precomposed.png"><!-- 57×57px -->
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-72x72-precomposed.png">
  <!-- For the iPad mini and the first- and second-generation iPad (@1× display) on iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-76x76-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-114x114-precomposed.png">
  <!-- For iPhone with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-120x120-precomposed.png">
  <!-- For iPad with @2× display running iOS ≤ 6: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-144x144-precomposed.png">
  <!-- For iPad with @2× display running iOS ≥ 7: -->
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-152x152-precomposed.png">
  <!-- For iPhone 6 Plus with @3× display: -->
  <link rel="apple-touch-icon-precomposed" sizes="180x180" href="/developer-rhino3d-com-branches/rebase/images/apple-touch-icon-180x180-precomposed.png">
  <!-- For Chrome for Android: -->
  <link rel="icon" sizes="192x192" href="images/touch-icon-192x192.png">

</head>


  <body>

    <!-- Google Tag Manager **This belongs right after the <body> tag**-->
    <noscript>
        <iframe src="//www.googletagmanager.com/ns.html?id=GTM-MWMDKN"
        height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <script>
        (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-MWMDKN');
    </script>
    <!-- End Google Tag Manager -->


    <div class="container">
      
<div class="version-banner">
  Hey, you're viewing the <strong>rebase</strong> version of this page!
  Click <a href="/developer-rhino3d-com-branches/samples/rhinocommon/furthestzonsurfacegivenxy/">here</a> to view the current (stable) version.
</div>



      <header class="site-header">


    <a class="site-title" href="/developer-rhino3d-com-branches/rebase/"><img src="/developer-rhino3d-com-branches/rebase/images/rhinodevlogo148x128.png" alt="Rhino Developer Docs" height="48" width="56"></a><a class="site-title" href="/developer-rhino3d-com-branches/rebase/">Rhino Developer Docs</a>

    <nav class="site-nav">
      <img class="menu-icon" src="/developer-rhino3d-com-branches/rebase/images/gi.svg">
      
      <div class="trigger">
      	<!--<a class="page-link" href="/developer-rhino3d-com-branches/rebase/">Welcome</a>-->
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
            
              
            
          
        
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/rebase/guides/">Guides</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/rebase/api/">API</a>
              
            
          
        
          
            
              
                <a class="page-link" href="/developer-rhino3d-com-branches/rebase/samples/">Samples</a>
              
            
          
        
          
            
          
        
        <a class="page-link" href="http://discourse.mcneel.com/c/rhino-developer">Forums</a>
        <!-- Google Search Engine -->
        <!-- TODO Move to this site back into the Mcneel search, or use a simple site only search for results -->
        <div id="sitesearch">
            <!-- Google CSE Search Box Begins  -->
            <!-- Use of this code assumes agreement with the Google Custom Search Terms of Service. -->
            <!-- The terms of service are available at https://www.google.com/cse/docs/tos.html -->
            <form id="cref" action="/developer-rhino3d-com-branches/rebase/search-results.html">
                <input type="hidden" name="cref" value="007988927381198593803:mcq6pshqsn8" />
                <input id="searchtext" type="text" name="q" size="24" value="" placeholder="search" />
                <input class="searchBox" type="submit" name="sa" size="2" value=" " />
            </form>
        <!-- Google CSE Search Box Ends -->
        </div>
        <!--End of Google Search Engine -->
      </div>
    </nav>

</header>


      <div class="page-content">
        <!--div class="wrapper"-->
          <h3>Determine Furthest Z on Surface given X Y</h3>

<p></p>

<ul class="nav nav-pills">
  <li class="active"><a href="#cs" data-toggle="pill">C#</a></li>
  <li><a href="#vb" data-toggle="pill">VB.NET</a></li>
  <li><a href="#py" data-toggle="pill">Python</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade in active highlighter-rouge" id="cs"><pre class="highlight"><code><span class="k">partial</span> <span class="k">class</span> <span class="nc">Examples</span>
<span class="p">{</span>
  <span class="k">public</span> <span class="k">static</span> <span class="n">Result</span> <span class="nf">FurthestZOnSurfaceGivenXY</span><span class="p">(</span><span class="n">RhinoDoc</span> <span class="n">doc</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="err">#</span><span class="n">region</span> <span class="n">user</span> <span class="n">input</span>
    <span class="c1">// select a surface
</span>    <span class="n">var</span> <span class="n">gs</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">GetObject</span><span class="p">();</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">SetCommandPrompt</span><span class="p">(</span><span class="s">"select surface"</span><span class="p">);</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">GeometryFilter</span> <span class="p">=</span> <span class="n">ObjectType</span><span class="p">.</span><span class="n">Surface</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">DisablePreSelect</span><span class="p">();</span>
    <span class="n">gs</span><span class="p">.</span><span class="n">SubObjectSelect</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
    <span class="n">gs</span><span class="p">.</span><span class="nf">Get</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">gs</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">()</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">gs</span><span class="p">.</span><span class="nf">CommandResult</span><span class="p">();</span>
    <span class="c1">// get the brep
</span>    <span class="n">var</span> <span class="n">brep</span> <span class="p">=</span> <span class="n">gs</span><span class="p">.</span><span class="nf">Object</span><span class="p">(</span><span class="m">0</span><span class="p">).</span><span class="nf">Brep</span><span class="p">();</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">brep</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Failure</span><span class="p">;</span>

    <span class="c1">// get X and Y
</span>    <span class="kt">double</span> <span class="n">x</span> <span class="p">=</span> <span class="m">0.0</span><span class="p">,</span> <span class="n">y</span> <span class="p">=</span> <span class="m">0.0</span><span class="p">;</span>
    <span class="n">var</span> <span class="n">rc</span> <span class="p">=</span> <span class="n">RhinoGet</span><span class="p">.</span><span class="nf">GetNumber</span><span class="p">(</span><span class="s">"value of X coordinate"</span><span class="p">,</span> <span class="k">true</span><span class="p">,</span> <span class="k">ref</span> <span class="n">x</span><span class="p">);</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">rc</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">rc</span><span class="p">;</span>
    <span class="n">rc</span> <span class="p">=</span> <span class="n">RhinoGet</span><span class="p">.</span><span class="nf">GetNumber</span><span class="p">(</span><span class="s">"value of Y coordinate"</span><span class="p">,</span> <span class="k">true</span><span class="p">,</span> <span class="k">ref</span> <span class="n">y</span><span class="p">);</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">rc</span> <span class="p">!=</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">)</span>
      <span class="k">return</span> <span class="n">rc</span><span class="p">;</span>
    <span class="err">#</span><span class="n">endregion</span>

    <span class="c1">// an earlier version of this sample used a curve-brep intersection to find Z
</span>    <span class="c1">//var maxZ = maxZIntersectionMethod(brep, x, y, doc.ModelAbsoluteTolerance);
</span>
    <span class="c1">// projecting points is another way to find Z
</span>    <span class="n">var</span> <span class="n">max_z</span> <span class="p">=</span> <span class="nf">MaxZProjectionMethod</span><span class="p">(</span><span class="n">brep</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">doc</span><span class="p">.</span><span class="n">ModelAbsoluteTolerance</span><span class="p">);</span>

    <span class="k">if</span> <span class="p">(</span><span class="n">max_z</span> <span class="p">!=</span> <span class="k">null</span><span class="p">)</span>
    <span class="p">{</span>
      <span class="n">RhinoApp</span><span class="p">.</span><span class="nf">WriteLine</span><span class="p">(</span><span class="s">"Maximum surface Z coordinate at X={0}, Y={1} is {2}"</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">max_z</span><span class="p">);</span>
      <span class="n">doc</span><span class="p">.</span><span class="n">Objects</span><span class="p">.</span><span class="nf">AddPoint</span><span class="p">(</span><span class="k">new</span> <span class="nf">Point3d</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">max_z</span><span class="p">.</span><span class="n">Value</span><span class="p">));</span>
      <span class="n">doc</span><span class="p">.</span><span class="n">Views</span><span class="p">.</span><span class="nf">Redraw</span><span class="p">();</span>
    <span class="p">}</span>
    <span class="k">else</span>
      <span class="n">RhinoApp</span><span class="p">.</span><span class="nf">WriteLine</span><span class="p">(</span><span class="s">"no maximum surface Z coordinate at X={0}, Y={1} found."</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">);</span>

    <span class="k">return</span> <span class="n">Result</span><span class="p">.</span><span class="n">Success</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="k">private</span> <span class="k">static</span> <span class="kt">double</span><span class="p">?</span> <span class="nf">MaxZProjectionMethod</span><span class="p">(</span><span class="n">Brep</span> <span class="n">brep</span><span class="p">,</span> <span class="kt">double</span> <span class="n">x</span><span class="p">,</span> <span class="kt">double</span> <span class="n">y</span><span class="p">,</span> <span class="kt">double</span> <span class="n">tolerance</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="kt">double</span><span class="p">?</span> <span class="n">max_z</span> <span class="p">=</span> <span class="k">null</span><span class="p">;</span>
    <span class="n">var</span> <span class="n">breps</span> <span class="p">=</span> <span class="k">new</span> <span class="n">List</span><span class="p">&lt;</span><span class="n">Brep</span><span class="p">&gt;</span> <span class="p">{</span><span class="n">brep</span><span class="p">};</span>
    <span class="n">var</span> <span class="n">points</span> <span class="p">=</span> <span class="k">new</span> <span class="n">List</span><span class="p">&lt;</span><span class="n">Point3d</span><span class="p">&gt;</span> <span class="p">{</span><span class="k">new</span> <span class="nf">Point3d</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="m">0</span><span class="p">)};</span>
    <span class="c1">// grab all the points projected in Z dir.  Aggregate finds furthest Z from XY plane
</span>    <span class="k">try</span> <span class="p">{</span>
      <span class="n">max_z</span> <span class="p">=</span> <span class="p">(</span><span class="n">from</span> <span class="n">pt</span> <span class="k">in</span> <span class="n">Intersection</span><span class="p">.</span><span class="nf">ProjectPointsToBreps</span><span class="p">(</span><span class="n">breps</span><span class="p">,</span> <span class="n">points</span><span class="p">,</span> <span class="k">new</span> <span class="nf">Vector3d</span><span class="p">(</span><span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">1</span><span class="p">),</span> <span class="n">tolerance</span><span class="p">)</span> <span class="n">select</span> <span class="n">pt</span><span class="p">.</span><span class="n">Z</span><span class="p">)</span>
              <span class="c1">// Here you might be tempted to use .Max() to get the largest Z value but that doesn't work because
</span>              <span class="c1">// Z might be negative.  This custom aggregate returns the max Z independant of the sign.  If it had a name
</span>              <span class="c1">// it could be MaxAbs()
</span>              <span class="p">.</span><span class="nf">Aggregate</span><span class="p">((</span><span class="n">z1</span><span class="p">,</span> <span class="n">z2</span><span class="p">)</span> <span class="p">=&gt;</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">z1</span><span class="p">)</span> <span class="p">&gt;</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">z2</span><span class="p">)</span> <span class="p">?</span> <span class="n">z1</span> <span class="p">:</span> <span class="n">z2</span><span class="p">);</span>
    <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="n">InvalidOperationException</span><span class="p">)</span> <span class="p">{</span><span class="cm">/*Sequence contains no elements*/</span><span class="p">}</span>
    <span class="k">return</span> <span class="n">max_z</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="k">private</span> <span class="k">static</span> <span class="kt">double</span><span class="p">?</span> <span class="nf">MaxZIntersectionMethod</span><span class="p">(</span><span class="n">Brep</span> <span class="n">brep</span><span class="p">,</span> <span class="kt">double</span> <span class="n">x</span><span class="p">,</span> <span class="kt">double</span> <span class="n">y</span><span class="p">,</span> <span class="kt">double</span> <span class="n">tolerance</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="kt">double</span><span class="p">?</span> <span class="n">max_z</span> <span class="p">=</span> <span class="k">null</span><span class="p">;</span>

    <span class="n">var</span> <span class="n">bbox</span> <span class="p">=</span> <span class="n">brep</span><span class="p">.</span><span class="nf">GetBoundingBox</span><span class="p">(</span><span class="k">true</span><span class="p">);</span>
    <span class="n">var</span> <span class="n">max_dist_from_xy</span> <span class="p">=</span> <span class="p">(</span><span class="n">from</span> <span class="n">corner</span> <span class="k">in</span> <span class="n">bbox</span><span class="p">.</span><span class="nf">GetCorners</span><span class="p">()</span> <span class="n">select</span> <span class="n">corner</span><span class="p">.</span><span class="n">Z</span><span class="p">)</span>
                            <span class="c1">// furthest Z from XY plane.
</span>                            <span class="c1">// Here you might be tempted to use .Max() to get the largest Z value but that doesn't work because
</span>                            <span class="c1">// Z might be negative.  This custom aggregate returns the max Z independant of the sign.  If it had a name
</span>                            <span class="c1">// it could be MaxAbs()
</span>                            <span class="p">.</span><span class="nf">Aggregate</span><span class="p">((</span><span class="n">z1</span><span class="p">,</span> <span class="n">z2</span><span class="p">)</span> <span class="p">=&gt;</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">z1</span><span class="p">)</span> <span class="p">&gt;</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">z2</span><span class="p">)</span> <span class="p">?</span> <span class="n">z1</span> <span class="p">:</span> <span class="n">z2</span><span class="p">);</span>
    <span class="c1">// multiply distance by 2 to make sure line intersects completely
</span>    <span class="n">var</span> <span class="n">line_curve</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">LineCurve</span><span class="p">(</span><span class="k">new</span> <span class="nf">Point3d</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="m">0</span><span class="p">),</span> <span class="k">new</span> <span class="nf">Point3d</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">max_dist_from_xy</span><span class="p">*</span><span class="m">2</span><span class="p">));</span>

    <span class="n">Curve</span><span class="p">[]</span> <span class="n">overlap_curves</span><span class="p">;</span>
    <span class="n">Point3d</span><span class="p">[]</span> <span class="n">inter_points</span><span class="p">;</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">Intersection</span><span class="p">.</span><span class="nf">CurveBrep</span><span class="p">(</span><span class="n">line_curve</span><span class="p">,</span> <span class="n">brep</span><span class="p">,</span> <span class="n">tolerance</span><span class="p">,</span> <span class="k">out</span> <span class="n">overlap_curves</span><span class="p">,</span> <span class="k">out</span> <span class="n">inter_points</span><span class="p">))</span>
    <span class="p">{</span>
      <span class="k">if</span> <span class="p">(</span><span class="n">overlap_curves</span><span class="p">.</span><span class="n">Length</span> <span class="p">&gt;</span> <span class="m">0</span> <span class="p">||</span> <span class="n">inter_points</span><span class="p">.</span><span class="n">Length</span> <span class="p">&gt;</span> <span class="m">0</span><span class="p">)</span>
      <span class="p">{</span>
        <span class="c1">// grab all the points resulting frem the intersection.
</span>        <span class="c1">//    1st set: points from overlapping curves,
</span>        <span class="c1">//    2nd set: points when there was no overlap
</span>        <span class="c1">//    .Aggregate: furthest Z from XY plane.
</span>        <span class="n">max_z</span> <span class="p">=</span> <span class="p">(</span><span class="n">from</span> <span class="n">c</span> <span class="k">in</span> <span class="n">overlap_curves</span> <span class="n">select</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">c</span><span class="p">.</span><span class="n">PointAtEnd</span><span class="p">.</span><span class="n">Z</span><span class="p">)</span> <span class="p">&gt;</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">c</span><span class="p">.</span><span class="n">PointAtStart</span><span class="p">.</span><span class="n">Z</span><span class="p">)</span> <span class="p">?</span> <span class="n">c</span><span class="p">.</span><span class="n">PointAtEnd</span><span class="p">.</span><span class="n">Z</span> <span class="p">:</span> <span class="n">c</span><span class="p">.</span><span class="n">PointAtStart</span><span class="p">.</span><span class="n">Z</span><span class="p">)</span>
                <span class="p">.</span><span class="nf">Union</span>
                <span class="p">(</span><span class="n">from</span> <span class="n">p</span> <span class="k">in</span> <span class="n">inter_points</span> <span class="n">select</span> <span class="n">p</span><span class="p">.</span><span class="n">Z</span><span class="p">)</span>
                 <span class="c1">// Here you might be tempted to use .Max() to get the largest Z value but that doesn't work because
</span>                 <span class="c1">// Z might be negative.  This custom aggregate returns the max Z independant of the sign.  If it had a name
</span>                 <span class="c1">// it could be MaxAbs()
</span>                <span class="p">.</span><span class="nf">Aggregate</span><span class="p">((</span><span class="n">z1</span><span class="p">,</span> <span class="n">z2</span><span class="p">)</span> <span class="p">=&gt;</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">z1</span><span class="p">)</span> <span class="p">&gt;</span> <span class="n">Math</span><span class="p">.</span><span class="nf">Abs</span><span class="p">(</span><span class="n">z2</span><span class="p">)</span> <span class="p">?</span> <span class="n">z1</span> <span class="p">:</span> <span class="n">z2</span><span class="p">);</span>
      <span class="p">}</span>
    <span class="p">}</span>
    <span class="k">return</span> <span class="n">max_z</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
</div>

<pre class="tab-pane fade in" id="vb"><code class="language-vbnet">Partial Friend Class Examples
  Public Shared Function FurthestZOnSurfaceGivenXY(ByVal doc As RhinoDoc) As Result
'	#Region "user input"
	' select a surface
	Dim gs = New GetObject()
	gs.SetCommandPrompt("select surface")
	gs.GeometryFilter = ObjectType.Surface
	gs.DisablePreSelect()
	gs.SubObjectSelect = False
	gs.Get()
	If gs.CommandResult() &lt;&gt; Result.Success Then
	  Return gs.CommandResult()
	End If
	' get the brep
	Dim brep = gs.Object(0).Brep()
	If brep Is Nothing Then
	  Return Result.Failure
	End If

	' get X and Y
	Dim x As Double = 0.0, y As Double = 0.0
	Dim rc = RhinoGet.GetNumber("value of X coordinate", True, x)
	If rc IsNot Result.Success Then
	  Return rc
	End If
	rc = RhinoGet.GetNumber("value of Y coordinate", True, y)
	If rc IsNot Result.Success Then
	  Return rc
	End If
'	#End Region

	' an earlier version of this sample used a curve-brep intersection to find Z
	'var maxZ = maxZIntersectionMethod(brep, x, y, doc.ModelAbsoluteTolerance);

	' projecting points is another way to find Z
	Dim max_z = MaxZProjectionMethod(brep, x, y, doc.ModelAbsoluteTolerance)

	If max_z IsNot Nothing Then
	  RhinoApp.WriteLine("Maximum surface Z coordinate at X={0}, Y={1} is {2}", x, y, max_z)
	  doc.Objects.AddPoint(New Point3d(x, y, max_z.Value))
	  doc.Views.Redraw()
	Else
	  RhinoApp.WriteLine("no maximum surface Z coordinate at X={0}, Y={1} found.", x, y)
	End If

	Return Result.Success
  End Function

  Private Shared Function MaxZProjectionMethod(ByVal brep As Brep, ByVal x As Double, ByVal y As Double, ByVal tolerance As Double) As Double?
	Dim max_z? As Double = Nothing
	Dim breps = New List(Of Brep) From {brep}
	Dim points = New List(Of Point3d) From {New Point3d(x, y, 0)}
	' grab all the points projected in Z dir.  Aggregate finds furthest Z from XY plane
	Try
	  max_z = (
	      From pt In Intersection.ProjectPointsToBreps(breps, points, New Vector3d(0, 0, 1), tolerance)
	      Select pt.Z).Aggregate(Function(z1, z2)If(Math.Abs(z1) &gt; Math.Abs(z2), z1, z2))
			  ' Here you might be tempted to use .Max() to get the largest Z value but that doesn't work because
			  ' Z might be negative.  This custom aggregate returns the max Z independant of the sign.  If it had a name
			  ' it could be MaxAbs()
	Catch e1 As InvalidOperationException 'Sequence contains no elements
	End Try
	Return max_z
  End Function

  Private Shared Function MaxZIntersectionMethod(ByVal brep As Brep, ByVal x As Double, ByVal y As Double, ByVal tolerance As Double) As Double?
	Dim max_z? As Double = Nothing

	Dim bbox = brep.GetBoundingBox(True)
	Dim max_dist_from_xy = (
	    From corner In bbox.GetCorners()
	    Select corner.Z).Aggregate(Function(z1, z2)If(Math.Abs(z1) &gt; Math.Abs(z2), z1, z2))
							' furthest Z from XY plane.
							' Here you might be tempted to use .Max() to get the largest Z value but that doesn't work because
							' Z might be negative.  This custom aggregate returns the max Z independant of the sign.  If it had a name
							' it could be MaxAbs()
	' multiply distance by 2 to make sure line intersects completely
	Dim line_curve = New LineCurve(New Point3d(x, y, 0), New Point3d(x, y, max_dist_from_xy*2))

	Dim overlap_curves() As Curve = Nothing
	Dim inter_points() As Point3d = Nothing
	If Intersection.CurveBrep(line_curve, brep, tolerance, overlap_curves, inter_points) Then
	  If overlap_curves.Length &gt; 0 OrElse inter_points.Length &gt; 0 Then
		' grab all the points resulting frem the intersection.
		'    1st set: points from overlapping curves,
		'    2nd set: points when there was no overlap
		'    .Aggregate: furthest Z from XY plane.
		max_z = (
		    From c In overlap_curves
		    Select If(Math.Abs(c.PointAtEnd.Z) &gt; Math.Abs(c.PointAtStart.Z), c.PointAtEnd.Z, c.PointAtStart.Z)).Union(
		    From p In inter_points
		    Select p.Z).Aggregate(Function(z1, z2)If(Math.Abs(z1) &gt; Math.Abs(z2), z1, z2))
				 ' Here you might be tempted to use .Max() to get the largest Z value but that doesn't work because
				 ' Z might be negative.  This custom aggregate returns the max Z independant of the sign.  If it had a name
				 ' it could be MaxAbs()
	  End If
	End If
	Return max_z
  End Function
End Class
</code></pre>

<div class="tab-pane fade in highlighter-rouge" id="py"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">rhinoscriptsyntax</span> <span class="kn">as</span> <span class="nn">rs</span>
<span class="kn">from</span> <span class="nn">Rhino.Geometry</span> <span class="kn">import</span> <span class="n">Intersect</span><span class="p">,</span> <span class="n">Point3d</span><span class="p">,</span> <span class="n">Vector3d</span>
<span class="kn">from</span> <span class="nn">scriptcontext</span> <span class="kn">import</span> <span class="n">doc</span>

<span class="k">def</span> <span class="nf">RunCommand</span><span class="p">():</span>
  <span class="c"># select a surface</span>
  <span class="n">srfid</span> <span class="o">=</span> <span class="n">rs</span><span class="o">.</span><span class="n">GetObject</span><span class="p">(</span><span class="s">"select serface"</span><span class="p">,</span> <span class="n">rs</span><span class="o">.</span><span class="nb">filter</span><span class="o">.</span><span class="n">surface</span> <span class="o">|</span> <span class="n">rs</span><span class="o">.</span><span class="nb">filter</span><span class="o">.</span><span class="n">polysurface</span><span class="p">)</span>
  <span class="k">if</span> <span class="ow">not</span> <span class="n">srfid</span><span class="p">:</span> <span class="k">return</span>
  <span class="c"># get the brep</span>
  <span class="n">brep</span> <span class="o">=</span> <span class="n">rs</span><span class="o">.</span><span class="n">coercebrep</span><span class="p">(</span><span class="n">srfid</span><span class="p">)</span>
  <span class="k">if</span> <span class="ow">not</span> <span class="n">brep</span><span class="p">:</span> <span class="k">return</span>

  <span class="n">x</span> <span class="o">=</span> <span class="n">rs</span><span class="o">.</span><span class="n">GetReal</span><span class="p">(</span><span class="s">"value of x"</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  <span class="n">y</span> <span class="o">=</span> <span class="n">rs</span><span class="o">.</span><span class="n">GetReal</span><span class="p">(</span><span class="s">"value of y"</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

  <span class="n">pts</span> <span class="o">=</span> <span class="p">[(</span><span class="nb">abs</span><span class="p">(</span><span class="n">point</span><span class="o">.</span><span class="n">Z</span><span class="p">),</span> <span class="n">point</span><span class="o">.</span><span class="n">Z</span><span class="p">)</span> <span class="k">for</span> <span class="n">point</span> <span class="ow">in</span> <span class="n">Intersect</span><span class="o">.</span><span class="n">Intersection</span><span class="o">.</span><span class="n">ProjectPointsToBreps</span><span class="p">(</span>
           <span class="p">[</span><span class="n">brep</span><span class="p">],</span> <span class="p">[</span><span class="n">Point3d</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="mi">0</span><span class="p">)],</span> <span class="n">Vector3d</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">),</span> <span class="n">doc</span><span class="o">.</span><span class="n">ModelAbsoluteTolerance</span><span class="p">)]</span>

  <span class="n">pts</span><span class="o">.</span><span class="n">sort</span><span class="p">(</span><span class="n">reverse</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>

  <span class="k">if</span> <span class="n">pts</span> <span class="o">==</span> <span class="p">[]:</span>
    <span class="k">print</span> <span class="s">"no Z for given X, Y"</span>
  <span class="k">else</span><span class="p">:</span>
    <span class="n">rs</span><span class="o">.</span><span class="n">AddPoint</span><span class="p">(</span><span class="n">Point3d</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">pts</span><span class="p">[</span><span class="mi">0</span><span class="p">][</span><span class="mi">1</span><span class="p">]))</span>

<span class="k">if</span> <span class="n">__name__</span> <span class="o">==</span> <span class="s">"__main__"</span><span class="p">:</span>
  <span class="n">RunCommand</span><span class="p">()</span>
</code></pre>
</div>

</div>

        <!--/div-->
      </div>

      <footer class="site-footer">

  <div class="wrapper">

    <div class="footer-col-wrapper">

      

        <div class="row">
          <div class="col-md-3">
              <span class="icon  icon--github">
                <svg viewBox="0 0 16 16">
                  <path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"/>
                </svg>
              </span>
              <a href="https://github.com/mcneel/developer-rhino3d-com-branches/blob/rebase/_samples/rhinocommon/furthestzonsurfacegivenxy.md" target="_blank">Edit on GitHub</a>
          </div>

          <div class="col-md-6 text-center">
            © 1997 - 2016 Robert McNeel &amp; Associates
          </div>

          <div class="col-md-3">
            <span class="pull-right">
              <span class="glyphicon glyphicon-cog"></span>&nbsp;<a href="/developer-rhino3d-com-branches/rebase/admin">Admin</a>
            </span>
          </div>

        </div>

      

    </div>

  </div>

  <script>
    if (navigator.appVersion.indexOf("Win")!=-1)
    {
      var body = document.getElementsByTagName("body");
      body[0].style.fontWeight = '400';
    }
  </script>

</footer>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <!-- MathJax -->
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    <script type="text/javascript">
    $('body').scrollspy({
        target: '.bs-docs-sidebar',
        offset: 150 /* fixed header is about 40px high */
    });
    </script>
  </body>

</html>
